-- Restore required privileges for Supabase Auth schema.
DO $$
BEGIN
  EXECUTE 'GRANT USAGE ON SCHEMA auth TO supabase_auth_admin';
  EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO supabase_auth_admin';
  EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA auth TO supabase_auth_admin';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO supabase_auth_admin';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT USAGE, SELECT ON SEQUENCES TO supabase_auth_admin';

  EXECUTE 'GRANT USAGE ON SCHEMA auth TO authenticator';
  EXECUTE 'GRANT SELECT ON ALL TABLES IN SCHEMA auth TO authenticator';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT ON TABLES TO authenticator';
END $$;
